# Generated by Django 5.1.7 on 2025-03-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
